### ISSUE TITLE
Turret control

### ISSUE THREAD

**Issue by LanCartwright** [Zaers/-tg-station#158]
Apparently this is broken, please check on it.

AI or carbon cannot disable or change turret settings.

**Comment by Koriath** [comment]
As in, when they click the control panel, or the turret itself?
Last night there was something weird going on, control panels weren't actually disabling turrets.
I'm pretty sure it's because of the recent name changes to areas, since control panels find turrets with those names. I'll take a look.

**Comment by Koriath** [comment]
Yeah, take a look:
if(!control_area)
		control_area = get_area(src)
	else if(istext(control_area))
		for(var/area/A in world)
			if(A.name && A.name==control_area)
				control_area = A
				break
Basically, if people changed the names of the area, you gotta change it on the control panel as well.
Otherwise, it is the wrong area, or defaults to the are the panel is in. In the upload, it would default to "Upload acess" instead of the actual upload area where the turrets are.
It's a mapping problem, should be an easy fix.
